# ======================================================================
#   Base Configuration for Single-Graph Datasets
# ======================================================================

# e.g. 'reddit', 'weibo', 'amazon', 'yelp', 'questions', 'tolokers', 'tfinance'
dataset: 'amazon_no_purify'

# --- 路径与设备 ---
data_dir: ./data
results_dir: ./results
save_dir: ./pretrained
checkpoint_dir: './checkpoints'
device: cuda

# --- 训练控制 ---
seed: 42
num_trials: 5
epochs: 100
patience: 30
batch_size: 64
composite_score_weights:
  AUPRC: 2.0   # 对于 Reddit，我们将 AUPRC 的权重设为 0
  AUROC: 0.5   # 将 AUROC 的权重设为 1.0，使其成为主导指标
  MacroF1: 0.0 # MacroF1 仍然不参与

# --- 模型与优化器 ---
lr: 5e-4
l2: 1e-5
hid_dim: 128
dropout: 0.3
activation: 'ReLU'
residual: True
norm: 'layernorm'
base_gnn_layers: 2
final_mlp_layers: 2
gna_proj_dim: 128

# --- 预训练模型架构 ---
pretrain_path: './pretrained/amazon_no_purify_enc_gcn2_dec_gcn1_e100_h128_loss_sce.pt'
pretrain_encoder_type: 'gcn'
pretrain_decoder_type: 'gcn'
pretrain_hid_dim: 128
pretrain_encoder_num_layer: 2
pretrain_decoder_num_layer: 1

# --- 预训练 PAA 参数 ---
pretrain_epochs: 100
pretrain_lr: 5e-3
pretrain_batch_size: 512
scheduler_step: 50
scheduler_gamma: 0.5
mask_ratio: 0.5
replace_ratio: 0.1
drop_edge_rate: 0.2
loss_fn: 'sce'
alpha_l: 2.0
w_contrastive: 0.5
w_recon: 1.0

# --- Uni-RHO-GAD 特定参数 ---
all_tasks: 'ne' # 单图任务
cross_modes: "ne2ne"
w_one_class: 2.0
w_gna: 1.0
w_classification: 1.0
w_classification_n: 2.0 # 提高节点任务的权重
w_classification_e: 0.5 # 降低边任务的权重

# 新增一个参数来控制是否冻结 RHOEncoder
freeze_rho_encoder: False

# --- 数据增强控制 ---
use_anomaly_generation: false
use_node_aug: false
use_edge_aug: false                                                           
# use_downstream_multi_graph_aug: False
aug_ratio: 0.5
aug_num_perturb_edges: 5
aug_feature_mix_ratio: 0.5